In [23]:
import pandas as pd

In [24]:
# Specify the file path
qualtrics = 'C:/Users/domin/Documents/GitHub/xai_budgeting/001_data/003_experiment/001_budget/118_qualtrics_results.csv'

# Load the .csv file into a DataFrame
qualtrics_df = pd.read_csv(qualtrics)

# Drop the observations without comment
qualtrics_df = qualtrics_df.dropna(subset=['Scenario1_Explainer', 'AI_Resubmission14', 'NoAI_Resubmission14'], how='all')

#Print overview
len(qualtrics_df)

118

In [25]:
qualtrics_df.head()

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Scenario1_FinalAnswer
0,08/03/2024 15:37,08/03/2024 15:45,IP Address,109.255.101.29,100,509,True,08/03/2024 15:45,R_42EVTwsQNiMtYLs,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179330
1,08/03/2024 15:40,08/03/2024 15:48,IP Address,90.211.114.152,100,500,True,08/03/2024 15:49,R_7Lh4y2eZkgRZuZl,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,160295
2,08/03/2024 15:40,08/03/2024 15:49,IP Address,82.40.42.60,100,539,True,08/03/2024 15:49,R_7mVlSS7HbwxkyXJ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,161903
3,08/03/2024 15:43,08/03/2024 15:50,IP Address,205.250.119.206,100,400,True,08/03/2024 15:50,R_5WPAWGujRgpokUh,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,162440
4,08/03/2024 15:45,08/03/2024 15:50,IP Address,86.145.73.224,100,274,True,08/03/2024 15:50,R_8odLgQVMrpe7TpX,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,160027

Create textfile for initial submissions

In [26]:
# Drop rows where all specified columns are NaN or empty
# Replace '' with NaN to also consider empty strings as NaN
qualtrics_df.replace('', pd.NA, inplace=True)
qualtrics_df.dropna(subset=['Scenario1_Explainer'], how='all', inplace=True)

# Select the specific columns you're interested in
subset_df = qualtrics_df[['Scenario1_Explainer']]

# Save these columns to a text file, using tab as a separator
subset_df.to_csv('C:/Users/domin/Documents/GitHub/xai_budgeting/001_data/003_experiment/002_justifications/initial_submission.txt', sep='\t', index=False)

# 'index=False' is used to prevent pandas from writing the DataFrame index into the file

Create text file for resubmissions

In [27]:
# Drop rows where all specified columns are NaN or empty
# Replace '' with NaN to also consider empty strings as NaN
qualtrics_df.replace('', pd.NA, inplace=True)
qualtrics_df.dropna(subset=[ 'AI_Resubmission14'], how='all', inplace=True)

# Select the specific columns you're interested in
subset_df = qualtrics_df[['AI_Resubmission14']]

# Save these columns to a text file, using tab as a separator
subset_df.to_csv('C:/Users/domin/Documents/GitHub/xai_budgeting/001_data/003_experiment/002_justifications/ai_resubmissions.txt', sep='\t', index=False)

# 'index=False' is used to prevent pandas from writing the DataFrame index into the file