In [111]:
import os
import pandas as pd
import numpy as np

# Import Files

### View the various tabs of the files

In [112]:
def list_tabs_in_excel_files(folder_path):
    # List to store the names of Excel files and their tabs
    excel_files_and_tabs = []

    # Iterate over the files in the specified folder
    for file in os.listdir(folder_path):
        # Check for both .xlsx and .xls files
        if file.endswith(('.xlsx', '.xls')):
            file_path = os.path.join(folder_path, file)
            try:
                # Load the Excel file
                xls = pd.ExcelFile(file_path)
                # Store the file name and its tabs
                excel_files_and_tabs.append((file, xls.sheet_names))
            except Exception as e:
                print(f"Error processing file {file}: {e}")

    return excel_files_and_tabs

In [113]:
# Specify folder location with .xls and .xlsx files
folder_path = r'C:\Users\domin\Documents\GitHub\xai_budgeting\data\raw'  # Use a raw string or properly escaped path
tabs_in_files = list_tabs_in_excel_files(folder_path)

# Print the list of files and their tabs
for file_name, tabs in tabs_in_files:
    print(f"File: {file_name}, Tabs: {tabs}")

File: kdkf_2001-2002_raw.xls, Tabs: ['ZH', 'BE', 'LU', 'UR', 'SZ', 'OW', 'NW', 'GL', 'ZG', 'FR', 'SO', 'BS', 'BL', 'SH', 'AR', 'AI', 'SG', 'GR', 'AG', 'TG', 'TI', 'VD', 'VS', 'NE', 'GE', 'JU', 'CHF', 'CHD', 'Abschlusszahlen Budget 2001', 'Abschlusszahlen Rechnung 2001', 'Abschlusszahlen Budgets 2002', 'Abschlusszahlen Rechnung 2002', 'Übersicht Saldo L. R. ', 'Finanzierungsfehlbetrag', 'Selbstfinanzierungsgrad', 'Erläuterung Kennzahlen']
File: kdkf_2003-2004_raw.xls, Tabs: ['ZH', 'BE', 'LU', 'UR', 'SZ', 'OW', 'NW', 'GL', 'ZG', 'FR', 'SO', 'BS', 'BL', 'SH', 'AR', 'AI', 'SG', 'GR', 'AG', 'TG', 'TI', 'VD', 'VS', 'NE', 'GE', 'JU', 'CHF', 'CHD', 'AbsschlusszahlenBudget 2003', 'Abschlusszahlen Rechnung 03', 'Abschlusszahlen Budgets 2004', 'Abschlusszahlen Rechnung 2004', 'Übersicht Saldo L. R. ', 'Finanzierungsfehlbetrag', 'Selbstfinanzierungsgrad', 'Erläuterung Kennzahlen']
File: kdkf_2005-2006_raw.xls, Tabs: ['ZH', 'BE', 'LU', 'UR', 'SZ', 'OW', 'NW', 'GL', 'ZG', 'FR', 'SO', 'BS', 'BL', 'SH', 'AR', 'AI', 'SG', 'GR', 'AG', 'TG', 'TI', 'VD', 'VS', 'NE', 'GE', 'JU', 'CHF', 'CHD', 'Abschlusszahlen Budget 2005', 'Abschlusszahlen Rechnung 2005', 'Abschlusszahlen Budgets 2006', 'Abschlusszahlen Rechnung 2006', 'Übersicht Saldo L. R. ', 'Finanzierungsfehlbetrag', 'Selbstfinanzierungsgrad']
File: kdkf_2007-2008_raw.xls, Tabs: ['Notiz', 'ZH', 'BE', 'LU', 'UR', 'SZ', 'OW', 'NW', 'GL', 'ZG', 'FR', 'SO', 'BS', 'BL', 'SH', 'AR', 'AI', 'SG', 'GR', 'AG', 'TG', 'TI', 'VD', 'VS', 'NE', 'GE', 'JU', 'CHF', 'CHD', 'Ergebnisse Budget 2007', 'Ergebnisse Rechnung 07', 'Ergebnisse Budgets 2008', 'Rechnung 2008', 'Übersicht Saldo L. R. ', 'Finanzierungsfehlbetrag', 'Selbstfinanzierungsgrad']
File: kdkf_2009_raw.xls, Tabs: ['ZH', 'BE', 'LU', 'UR', 'SZ', 'OW', 'NW', 'GL', 'ZG', 'FR', 'SO', 'BS', 'BL', 'SH', 'AR', 'AI', 'SG', 'GR', 'AG', 'TG', 'TI', 'VD', 'VS', 'NE', 'GE', 'JU', 'CHF', 'CHD', 'Ergebnisse Rechnung 2008', 'Ergebnisse Budgets 2009', 'Ergebnisse Rechnung 2009', 'Budget 2010', 'Übersicht Saldo L. R. ', 'Finanzierungsfehlbetrag', 'Selbstfinanzierungsgrad']
File: kdkf_2010_raw.xls, Tabs: ['ZH-HRM2', 'BE', 'LU', 'UR', 'SZ', 'OW', 'NW', 'NW-HRM2', 'GL', 'GL-HRM2', 'ZG', 'FR', 'SO', 'BS', 'BL', 'BL-HRM2', 'SH', 'AR', 'AI', 'SG', 'GR', 'AG', 'TG', 'TI', 'VD', 'VS', 'NE', 'GE', 'JU', 'CHF', 'CHD', 'Ergebnisse Rechnung 2009', 'Ergebnisse Budgets 2010', 'Ergebnisse Rechnung 2010', 'Budget 2011', 'Übersicht Saldo L. R. ', 'Finanzierungsfehlbetrag', 'Selbstfinanzierungsgrad']
File: kdkf_2011_raw.xls, Tabs: ['ZH HRM2', 'BE HRM1', 'LU HRM1', 'LU HRM2', 'UR HRM1', 'UR HRM2', 'SZ HRM1', 'OW HRM1', 'NW HRM2', 'GL HRM1', 'GL HRM2', 'ZG HRM1', 'ZG HRM2', 'FR MCH1', 'FR MCH2', 'SO HRM1', 'SO HRM2', 'BS HRM1', 'BL HRM2', 'SH HRM1', 'AR HRM1', 'AI HRM1', 'SG HRM1', 'GR HRM1', 'AG HRM1', 'TG HRM1', 'TG HRM2', 'TI HRM1', 'VD MCH1', 'VS MCH1', 'NE MCH1', 'GE IPSAS', 'JU MCH1', 'JU MCH2', 'CHF', 'CHD', 'Ergebnisse Rechnung 2010', 'Ergebnisse Budgets 2011', 'Ergebnisse Rechnung 2011', 'Budget 2012', 'Übersicht Saldo L. R. ', 'Finanzierungsfehlbetrag', 'Selbstfinanzierungsgrad']
File: kdkf_2012_raw.xls, Tabs: ['ZH HRM2', 'BE HRM1', 'LU HRM1', 'LU HRM2', 'UR HRM1', 'UR HRM2', 'SZ HRM1', 'OW HRM1', 'OW HRM2', 'NW HRM2', 'GL HRM2', 'ZG HRM1', 'ZG HRM2', 'FR MCH2', 'SO HRM1', 'SO HRM2', 'BS HRM1', 'BS HRM2', 'BL HRM2', 'SH HRM1', 'AR HRM1', 'AR HRM2', 'AI HRM1', 'SG HRM1', 'GR HRM1', 'GR HRM2', 'AG HRM1', 'TG HRM1', 'TG HRM2', 'TI HRM1', 'VD MCH1', 'VS MCH1', 'NE MCH1', 'GE IPSAS', 'JU MCH1', 'JU MCH2', 'CHF', 'CHD', 'Ergebnisse Rechnung 2011', 'Ergebnisse Budgets 2012', 'Ergebnisse Rechnung 2012', 'Budget 2013', 'Übersicht Saldo L. R. ', 'Finanzierungsfehlbetrag', 'Selbstfinanzierungsgrad']
File: kdkf_2013_raw.xlsx, Tabs: ['ZH HRM2', 'BE HRM1', 'LU HRM2', 'UR HRM2', 'SZ HRM1', 'OW HRM2', 'NW HRM2', 'GL HRM2', 'ZG HRM2', 'FR HRM2', 'SO HRM2', 'BS HRM1', 'BS HRM2', 'BL HRM2', 'SH HRM1', 'AR HRM1', 'AR HRM2', 'AI HRM1', 'SG HRM1', 'SG HRM2', 'GR HRM1', 'GR HRM2', 'AG HRM1', 'AG HRM2', 'TG HRM2', 'TI MCH1', 'TI MCH2', 'VD MCH1', 'VD MCH2', 'VS MCH1', 'NE MCH1', 'GE MCH1', 'GE IPSAS', 'JU MCH2', 'Rechnung 2012', 'Budget 2013', 'Rechnung 2013', 'Budget 2014', 'Übersicht Saldo L. R. ', 'Finanzierungsfehlbetrag', 'Selbstfinanzierungsgrad', 'CHF', 'CHD']
File: kdkf_2014_raw.xlsx, Tabs: ['ZH HRM2', 'BE HRM1', 'LU HRM2', 'UR HRM2', 'SZ HRM1', 'OW HRM2', 'NW HRM2', 'GL HRM2', 'ZG HRM2', 'FR HRM2', 'SO HRM2', 'BS HRM2', 'BL HRM2', 'SH HRM1', 'AR HRM2', 'AI HRM1', 'AI HRM2', 'Sg HRM1', 'SG HRM2', 'GR HRM2', 'AG HRM1', 'AG HRM2', 'TG HRM2', 'TI HRM1', 'TI HRM2', 'VD HRM1', 'VD HRM2', 'VS HRM1', 'NE HRM1', 'GE HRM2', 'JU HRM2', 'Ergebnisse Rechnung 2013', 'Ergebnisse Budgets 2014', 'Ergebnisse Rechnung 2014', 'Budget 2015', 'Übersicht Saldo L. R. ', 'Finanzierungsfehlbetrag', 'Selbstfinanzierungsgrad', 'CHF', 'CHD']
File: kdkf_2015_raw.xlsx, Tabs: ['ZH_HRM2', 'BE HRM1', 'LU_HRM2', 'UR_HRM2', 'SZ HRM1', 'SZ_HRM2', 'OW_HRM2', 'NW_HRM2', 'GL_HRM2', 'ZG_HRM2', 'FR_HRM2', 'SO_HRM2', 'BS_HRM2', 'BL_HRM2', 'SH HRM1', 'AR_HRM2 ', 'AI HRM1', 'AI_HRM2', 'SG_HRM2', 'GR_HRM2', 'AG_HRM2', 'TG_HRM2', 'TI_HRM2', 'VD_HRM2', 'VS HRM1', 'NE HRM1', 'GE_HRM2', 'JU_HRM2', 'CHF', 'CHD', 'Ergebnisse Rechnung 2014', 'Ergebnisse Budgets 2015', 'Ergebnisse Rechnung 2015', 'Budget 2016', 'Übersicht Saldo L. R. ', 'Finanzierungsfehlbetrag', 'Selbstfinanzierungsgrad']
File: kdkf_2016_raw.xlsx, Tabs: ['ZH_HRM2', 'BE HRM1', 'BE_HRM2', 'LU_HRM2', 'UR_HRM2', 'SZ_HRM2', 'OW_HRM2', 'NW_HRM2', 'GL_HRM2', 'ZG_HRM2', 'FR_HRM2', 'SO_HRM2', 'BS_HRM2', 'BL_HRM2', 'SH_HRM1', 'AR_HRM2', 'AI_HRM2', 'SG_HRM2', 'GR_HRM2', 'AG_HRM2', 'TG_HRM2', 'TI_HRM2', 'VD_HRM2', 'VS_HRM1', 'NE_HRM1', 'GE_HRM2', 'JU_HRM2', 'CHF_HRM1', 'CHD_HRM1', 'Rechnung 2015', 'Budgets 2016', 'Rechnung 2016', 'Budget 2017', 'Übersicht Saldo L. R. ', 'Finanzierungsfehlbetrag', 'Selbstfinanzierungsgrad']
File: kdkf_2017_raw.xlsx, Tabs: ['ZH_HRM2', 'AG_HRM2', 'AI_HRM2', 'AR_HRM2', 'BE_HRM1', 'BE_HRM2', 'BL_HRM2', 'BS_HRM2', 'FR_HRM2', 'GE_HRM2', 'GL_HRM2', 'GR_HRM2', 'JU_HRM2', 'LU_HRM2', 'NE_HRM1', 'NE_HRM2', 'NW_HRM2', 'OW_HRM2', 'SG_HRM2', 'SH_HRM1', 'SH_HRM2', 'SO_HRM2', 'SZ_HRM2', 'TG_HRM2', 'TI_HRM2', 'UR_HRM2', 'VD_HRM2', 'VS_HRM1', 'VS_HRM2', 'ZG_HRM2', 'CHF', 'CHD', 'Ergebnisse Rechnung 2016', 'Ergebnisse Budgets 2017', 'Ergebnisse Rechnung 2017', 'Budget 2018', 'Übersicht Saldo L. R. ', 'Finanzierungsfehlbetrag', 'Selbstfinanzierungsgrad']
File: kdkf_2018_raw.xlsx, Tabs: ['ZH_HRM2', 'BE_HRM2', 'LU_HRM2', 'UR_HRM2', 'SZ_HRM2', 'OW_HRM2', 'NW_HRM2', 'GL_HRM2', 'ZG_HRM2', 'FR_HRM2', 'SO_HRM2', 'BS_HRM2', 'BL_HRM2', 'SH_HRM2', 'SH', 'AR_HRM2', 'AI_HRM2', 'SG_HRM2', 'GR_HRM2', 'AG_HRM2', 'TG_HRM2', 'TI_HRM2', 'VD_HRM2', 'VS_HRM2', 'VS', 'NE_HRM2', 'NE', 'GE_HRM2', 'JU_HRM2', 'CHF', 'CHD', 'Ergebnisse Rechnung 2017', 'Ergebnisse Budgets 2018', 'Ergebnisse Rechnung 2018', 'Budget 2019', 'Übersicht Saldo L. R. ', 'Finanzierungsfehlbetrag', 'Selbstfinanzierungsgrad']
File: kdkf_2019_raw.xlsx, Tabs: ['Abschlusszahlen_RG_Jahr-1', 'Abschlusszahlen_BUD_Jahr', 'Abschlusszahlen_RG_Jahr', 'Abschlusszahlen_BUD_Jahr+1', 'Saldo_Laufende_RG', 'Finanzierung', 'Selbstfinanzierungsgrad', 'HRM2_KT_alle', 'HRM2_KT_AG', 'HRM2_KT_AI', 'HRM2_KT_AR', 'HRM2_KT_BE', 'HRM2_KT_BL', 'HRM2_KT_BS', 'HRM2_KT_FR', 'HRM2_KT_GE', 'HRM2_KT_GL', 'HRM2_KT_GR', 'HRM2_KT_JU', 'HRM2_KT_LU', 'HRM2_KT_NE', 'HRM2_KT_NW', 'HRM2_KT_OW', 'HRM2_KT_SG', 'HRM2_KT_SH', 'HRM2_KT_SO', 'HRM2_KT_SZ', 'HRM2_KT_TG', 'HRM2_KT_TI', 'HRM2_KT_UR', 'HRM2_KT_VD', 'HRM2_KT_VS', 'HRM2_KT_ZG', 'HRM2_KT_ZH']
File: kdkf_2020_raw.xlsx, Tabs: ['HRM2_KT_alle', 'HRM2_KT_AG', 'HRM2_KT_AI', 'HRM2_KT_AR', 'HRM2_KT_BE', 'HRM2_KT_BL', 'HRM2_KT_BS', 'HRM2_KT_FR', 'HRM2_KT_GE', 'HRM2_KT_GL', 'HRM2_KT_GR', 'HRM2_KT_JU', 'HRM2_KT_LU', 'HRM2_KT_NE', 'HRM2_KT_NW', 'HRM2_KT_OW', 'HRM2_KT_SG', 'HRM2_KT_SH', 'HRM2_KT_SO', 'HRM2_KT_SZ', 'HRM2_KT_TG', 'HRM2_KT_TI', 'HRM2_KT_UR', 'HRM2_KT_VD', 'HRM2_KT_VS', 'HRM2_KT_ZG', 'HRM2_KT_ZH', 'Abschlusszahlen_RG_Jahr-1', 'Abschlusszahlen_BUD_Jahr', 'Abschlusszahlen_RG_Jahr', 'Abschlusszahlen_BUD_Jahr+1', 'Gesamtergebnis_ER', 'Finanzierungsergebnis', 'Selbstfinanzierungsgrad']
File: kdkf_2021_raw.xlsx, Tabs: ['HRM2_KT_alle', 'HRM2_KT_AG', 'HRM2_KT_AI', 'HRM2_KT_AR', 'HRM2_KT_BE', 'HRM2_KT_BL', 'HRM2_KT_BS', 'HRM2_KT_FR', 'HRM2_KT_GE', 'HRM2_KT_GL', 'HRM2_KT_GR', 'HRM2_KT_JU', 'HRM2_KT_LU', 'HRM2_KT_NE', 'HRM2_KT_NW', 'HRM2_KT_OW', 'HRM2_KT_SG', 'HRM2_KT_SH', 'HRM2_KT_SO', 'HRM2_KT_SZ', 'HRM2_KT_TG', 'HRM2_KT_TI', 'HRM2_KT_UR', 'HRM2_KT_VD', 'HRM2_KT_VS', 'HRM2_KT_ZG', 'HRM2_KT_ZH', 'Abschlusszahlen_RG_Jahr-1', 'Abschlusszahlen_BUD+_Jahr', 'Abschlusszahlen_RG_Jahr', 'Abschlusszahlen_BUD_Jahr+1', 'Gesamtergebnis_ER', 'Finanzierungsergebnis', 'Selbstfinanzierungsgrad']
File: kdkf_2022_raw.xlsx, Tabs: ['HRM2_KT_alle', 'HRM2_KT_AG', 'HRM2_KT_AI', 'HRM2_KT_AR', 'HRM2_KT_BE', 'HRM2_KT_BL', 'HRM2_KT_BS', 'HRM2_KT_FR', 'HRM2_KT_GE', 'HRM2_KT_GL', 'HRM2_KT_GR', 'HRM2_KT_JU', 'HRM2_KT_LU', 'HRM2_KT_NE', 'HRM2_KT_NW', 'HRM2_KT_OW', 'HRM2_KT_SG', 'HRM2_KT_SH', 'HRM2_KT_SO', 'HRM2_KT_SZ', 'HRM2_KT_TG', 'HRM2_KT_TI', 'HRM2_KT_UR', 'HRM2_KT_VD', 'HRM2_KT_VS', 'HRM2_KT_ZG', 'HRM2_KT_ZH', 'Abschlusszahlen_RG_Jahr-1', 'Abschlusszahlen_BUD+_Jahr', 'Abschlusszahlen_RG_Jahr', 'Abschlusszahlen_BUD_Jahr+1', 'Gesamtergebnis_ER', 'Finanzierungsergebnis', 'Selbstfinanzierungsgrad']

### Load Testfile and extract data

In [114]:
# Define the file path and the sheet name
file_path = r'C:\Users\domin\Documents\GitHub\xai_budgeting\data\raw\kdkf_2022_raw.xlsx'  # Use a raw string for the file path
sheet_name = 'HRM2_KT_AG'

# Load the specified sheet into a DataFrame
hrm2_kt_ag = pd.read_excel(file_path, sheet_name=sheet_name, skiprows=3) # Skip the first three rows as these are solely headers

# Display the first few rows of the DataFrame
hrm2_kt_ag.head()

,Unnamed: 0,Aargau,Unnamed: 2,Rechnung,Budget*,Anpassung Budget**,Budgetplus***,Rechnung.1,Budget
0,Referenz-ID,HRM 2,in 1 000 Franken,2021.00000,2022.00000,2022.00000,2022.00000,2022.00000,2023.00000
1,ER,ERFOLGSRECHNUNG,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HRM2_ER0030,30,Personalaufwand,1710857.49536,1824800.67300,47003.56600,1871804.23900,1769407.06614,1913008.92200
3,HRM2_ER0031,31,Sach- und übriger Betriebsaufwand,465105.56175,486337.94000,66409.52300,552747.46300,471235.72459,540895.28650
4,HRM2_ER0314,davon 314,baulicher und betrieblicher Unterhalt,40709.52698,38381.36200,1000.00000,39381.36200,36143.20582,38863.24700

In [115]:
# Set the pandas option to display floating point numbers using the decimal format
pd.options.display.float_format = '{:.5f}'.format

In [116]:
# Merge the first row with the column headers in a dataframe
hrm2_kt_ag.columns = hrm2_kt_ag.iloc[0, :2].tolist() + (hrm2_kt_ag.columns[2:]).tolist()
hrm2_kt_ag = hrm2_kt_ag.iloc[1:].reset_index(drop=True) 
hrm2_kt_ag.head()

,Referenz-ID,HRM 2,Unnamed: 2,Rechnung,Budget*,Anpassung Budget**,Budgetplus***,Rechnung.1,Budget
0,ER,ERFOLGSRECHNUNG,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HRM2_ER0030,30,Personalaufwand,1710857.49536,1824800.67300,47003.56600,1871804.23900,1769407.06614,1913008.92200
2,HRM2_ER0031,31,Sach- und übriger Betriebsaufwand,465105.56175,486337.94000,66409.52300,552747.46300,471235.72459,540895.28650
3,HRM2_ER0314,davon 314,baulicher und betrieblicher Unterhalt,40709.52698,38381.36200,1000.00000,39381.36200,36143.20582,38863.24700
4,HRM2_ER0318,davon 3180,Wertberichtigungen auf Forderungen,1524.78485,1550.00000,0.00000,1550.00000,-1948.07897,1483.50000

In [119]:
# Update Headers of the df

# Define the years
previous_year = 2021
start_year = 2022
target_year = 2023

# Mapping of old column names to new column names
rename_dict = {
    'Unnamed: 2': 'in 1000 CHF',
    'Rechnung': f'Rechnung {previous_year}',
    'Budget*': f'Budget {start_year}',
    'Anpassung Budget**': f'Anpassung Budget {start_year}',
    'Budgetplus***': f'Budgetplus {start_year}',
    'Rechnung.1': f'Rechnung {start_year}',
    'Budget': f'Budget {target_year}'
}

# Rename the columns
hrm2_kt_ag.rename(columns=rename_dict, inplace=True)

# Display the first few rows of the DataFrame with updated column names
hrm2_kt_ag.head()

,Referenz-ID,HRM 2,in 1000 CHF,Rechnung 2021,Budget 2022,Anpassung Budget 2022,Budgetplus 2022,Rechnung 2022,Budget 2023
0,ER,ERFOLGSRECHNUNG,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HRM2_ER0030,30,Personalaufwand,1710857.49536,1824800.67300,47003.56600,1871804.23900,1769407.06614,1913008.92200
2,HRM2_ER0031,31,Sach- und übriger Betriebsaufwand,465105.56175,486337.94000,66409.52300,552747.46300,471235.72459,540895.28650
3,HRM2_ER0314,davon 314,baulicher und betrieblicher Unterhalt,40709.52698,38381.36200,1000.00000,39381.36200,36143.20582,38863.24700
4,HRM2_ER0318,davon 3180,Wertberichtigungen auf Forderungen,1524.78485,1550.00000,0.00000,1550.00000,-1948.07897,1483.50000

In [121]:
# Filter the DataFrame to keep only rows where 'Referenz-ID' contains 'HRM2'
hrm2_kt_ag = hrm2_kt_ag[hrm2_kt_ag['Referenz-ID'].str.contains('HRM2', na=False)]

# Display the first few rows of the DataFrame to verify the changes
hrm2_kt_ag

,Referenz-ID,HRM 2,in 1000 CHF,Rechnung 2021,Budget 2022,Anpassung Budget 2022,Budgetplus 2022,Rechnung 2022,Budget 2023
1,HRM2_ER0030,30,Personalaufwand,1710857.49536,1824800.67300,47003.56600,1871804.23900,1769407.06614,1913008.92200
2,HRM2_ER0031,31,Sach- und übriger Betriebsaufwand,465105.56175,486337.94000,66409.52300,552747.46300,471235.72459,540895.28650
3,HRM2_ER0314,davon 314,baulicher und betrieblicher Unterhalt,40709.52698,38381.36200,1000.00000,39381.36200,36143.20582,38863.24700
4,HRM2_ER0318,davon 3180,Wertberichtigungen auf Forderungen,1524.78485,1550.00000,0.00000,1550.00000,-1948.07897,1483.50000
5,HRM2_neu_ER0033,33,Abschreibungen VV,264389.83000,201998.18638,0.00000,201998.18638,176835.45829,162266.45182
...,...,...,...,...,...,...,...,...,...
205,HRM2_KZ18_12,HRM2-Tabelle 18.12,Gesamteinnahmen,5749681.16529,5424135.51185,0.00000,5468190.44485,5826118.76115,5389544.72900
206,HRM2_KZ18_15,HRM2-Tabelle 18.15,Laufende Ausgaben,5072349.35397,5066781.14300,0.00000,5223709.47600,5294503.70695,5361025.20850
207,HRM2_KZ18_11,HRM2-Tabelle 18.11,Gesamtausgaben,5390875.82542,5422015.95805,0.00000,5586768.01205,5584185.98046,5666084.24485
208,HRM2_KZEFRLZ,NaN,Ergebnis Finanzrechnung Laufende Zahlungen,594052.34468,273521.21085,0.00000,160647.81085,452644.19696,-41249.59750
209,HRM2_KZEFRG,NaN,Ergebnis Finanzrechnung Gesamt,358805.33987,2119.55380,0.00000,-118577.56720,241932.78069,-276539.51585