In [1]:
import pandas as pd
import numpy as np

/var/folders/vy/kftwr_sx3kjbxvnd1nvc851m0000gn/T/ipykernel_84177/2162656668.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
file_path = "../data/raw/kdkf_2016_raw.xlsx"

In [3]:
df = pd.read_excel(file_path, sheet_name="SH_HRM1", header=1)

In [4]:
df.head()

,0,0.1,2015,in %,2016,in %.1,2016.1,in %.2,2017
0,0,L A U F E N D E R E C H N U N G,0.00000,0,0.0,0,0.000,0,0.0
1,30,Personalaufwand,170690.58737,0.021355,174335.6,-0.003825,173668.702,0.003445,174267.0
2,31,Sachaufwand,59086.52689,0.006911,59494.9,-0.011354,58819.409,0.002793,58983.7
3,davon 314,Baulicher Unterhalt,7668.53859,-0.16327,6416.5,0.020455,6547.749,0.005979,6586.9
4,32,Passivzinsen,1925.31005,0.486877,2862.7,-0.39881,1721.028,0.24199,2137.5

In [5]:
def rename_columns_based_on_year(
        df: pd.DataFrame, base_year: str
    ) -> pd.DataFrame:
        # Define the base renaming dictionary
        renaming_dict = {
            "0": "Acc-ID",
            "0.1": "Name",
            f"{base_year}": "Budget y",
            f"{base_year}.1": "Realized",
            str(int(base_year) + 1): "Budget y+1",
        }

        df.columns = df.columns.map(str)

        # Filter out columns not in the renaming dictionary
        df = df[df.columns.intersection(renaming_dict.keys())]

        # Rename the columns
        df = df.rename(columns=renaming_dict)

        return df

In [6]:
df = df.drop(df.index[0])
df = rename_columns_based_on_year(df, 2016)

In [7]:
df

,Acc-ID,Name,Budget y,Realized,Budget y+1
1,30,Personalaufwand,174335.600000,173668.702000,174267.00000
2,31,Sachaufwand,59494.900000,58819.409000,58983.70000
3,davon 314,Baulicher Unterhalt,6416.500000,6547.749000,6586.90000
4,32,Passivzinsen,2862.700000,1721.028000,2137.50000
5,330,Abschreibungen Finanzvermögen,3615.000000,3574.686000,3665.00000
6,331 - 333,Abschreibungen Verwaltungsvermögen,18425.700000,22119.987000,19325.90000
7,34 - 37,"Anteile, Entschädigungen, Beiträge",388946.800000,384609.470000,394565.00000
8,davon 363,Beiträge an eigene Anstalten,61524.700000,62965.850000,63322.30000
9,davon 364,Beiträge an gemischtwirtschaftliche Unternehmu...,2450.000000,2394.172000,2502.00000
10,davon 365,Beiträge an private Institutionen,133187.100000,129856.778000,135662.70000
11,davon 373,Durchl. Beiträge an eigene Anstalten,0.000000,0.000000,0.00000
12,davon 374,Durchl. Beiträge an gemischtwirtschaftliche Un...,0.000000,0.000000,0.00000
13,davon 375,Durchl. Beiträge an private Institutionen,700.000000,871.098000,924.30000
14,38,Einlagen in Spezialfinanzierungen/Fonds,14949.000000,22073.590000,16501.00000
15,389,Einlagen in das Eigenkapital,0.000000,33100.000000,0.00000
16,39,Interne Verrechnungen (Aufwand),21785.300000,22559.886000,23699.70000
17,3,Total Aufwand Laufende Rechnung,684415.000000,722246.758000,693144.80000
18,400 - 404,Direkte Steuern,304700.000000,340337.569000,314000.00000
19,405 - 407,Uebrige Steuern,19635.000000,21261.685000,20717.00000
20,42,Vermögenserträge,36867.100000,54553.306000,35386.90000
21,41 / 43,Konzessionen/Entgelte (Gebühren),70578.500000,71363.059000,70734.60000
22,44 - 47,"Anteile, Rückerstattungen, Beiträge",206686.700000,222155.044000,219466.60000
23,48,Entnahme aus Spezialfinanzierungen,8039.200000,6608.092000,4949.10000
24,489,Entnahmen aus dem Eigenkapital,0.000000,0.000000,0.00000
25,49,Interne Verrechnungen (Ertrag),21785.300000,22559.886000,23699.70000
26,4,Total Ertrag Laufende Rechnung,668291.800000,738838.641000,688953.90000
27,.,Saldo Laufende Rechnung,-16123.200000,16591.883000,-4190.90000
28,0,I N V E S T I T I O N S R E C H N U N G,0.000000,0.000000,0.00000
29,50,Sachgüter,13420.000000,9924.023000,21685.00000
30,52,Darlehen und Beteiligungen,60.000000,20169.200000,760.00000
31,56 - 58,"Investitionsbeiträge,übrige Investitionen",19310.000000,7369.561000,10510.00000
32,5,Total Ausgaben Investitionsrechnung,32790.000000,37462.784000,32955.00000
33,60 - 61,"Abgang Sachgüter, Nutzungsabgaben",0.000000,13877.371000,0.00000
34,62 - 67,"Rückzahlung,Rückerstattung,Invest.-Beitr.",7752.200000,7591.648000,18392.60000
35,6,Total Einnahmen Investitionsrechnung,7752.200000,21469.019000,18392.60000
36,NI,Nettoinvestition,25037.800000,15993.765000,14562.40000
37,,Selbstfinanzierung,2302.500000,71811.870000,15135.00000
38,,Finanzierungsfehlbetrag(-)/-überschuss(+),-22735.300000,55818.105000,572.60000
39,,Konsolidierte Gesamtausgaben,658430.000000,656281.393000,662908.20000
40,0,Selbstfinanzierungsgrad,0.091961,4.489992,1.03932

In [8]:
hrm1_to_hrm2_dict = {
    "1": (["1"], [1.0]),
    "2": (["2"], [1.0]),
    "3": (["3"], [1.0]),
    "4": (["4"], [1.0]),
    "5": (["5"], [1.0]),
    "6": (["6"], [1.0]),
    "30": (["30"], [1.0]),
    "31": (["31"], [1.0]),
    "33": (["33"], [1.0]),
    "38": (["35"], [1.0]),
    "34 - 37": (["34", "35", "36", "37"], [0.25, 0.25, 0.25, 0.25]),
    "39": (["39"], [1.0]),
    "40": (["40"], [1.0]),
    "41 / 43": (["41", "43"], [0.5, 0.5]),
    "48": (["45"], [1.0]),
    "44 - 47": (["44", "45", "46", "47"], [0.25, 0.25, 0.25, 0.25]),
    "49": (["49"], [1.0]),
    "32": (["34"], [1.0]),
    "50": (["50"], [1.0]),
    "52": (["54"], [1.0]),
    "56 - 58": (["56", "57", "58"], [1/3, 1/3, 1/3]),
    "60 - 61": (["60", "61"], [0.5, 0.5]),
    "62 - 67": (["62", "63", "64", "65", "66", "67"], [1/6, 1/6, 1/6, 1/6, 1/6, 1/6])
}

In [9]:
new_rows = []

for index, row in df.iterrows():
    old_acc_id = row['Acc-ID']
    
    # Check if the Acc-ID is a range and needs splitting
    if old_acc_id in hrm1_to_hrm2_dict:
        new_acc_ids, ratios = hrm1_to_hrm2_dict[old_acc_id]
        splits = len(new_acc_ids)

        for new_acc_id, ratio in zip(new_acc_ids, ratios):
            new_row = row.copy()
            new_row['Acc-ID'] = new_acc_id
            new_row['Budget y'] *= ratio
            new_row['Realized'] *= ratio
            new_row['Budget y+1'] *= ratio
            new_rows.append(new_row.to_dict())
    else:
        # Handle cases where Acc-ID is not in the mapping
        new_rows.append(row)

In [10]:
new_df = pd.DataFrame(new_rows, index=None)

In [13]:
new_df

,Acc-ID,Name,Budget y,Realized,Budget y+1
0,30,Personalaufwand,174335.600000,173668.702000,174267.000000
1,31,Sachaufwand,59494.900000,58819.409000,58983.700000
2,davon 314,Baulicher Unterhalt,6416.500000,6547.749000,6586.900000
3,34,Passivzinsen,2862.700000,1721.028000,2137.500000
4,330,Abschreibungen Finanzvermögen,3615.000000,3574.686000,3665.000000
5,331 - 333,Abschreibungen Verwaltungsvermögen,18425.700000,22119.987000,19325.900000
6,34,"Anteile, Entschädigungen, Beiträge",97236.700000,96152.367500,98641.250000
7,35,"Anteile, Entschädigungen, Beiträge",97236.700000,96152.367500,98641.250000
8,36,"Anteile, Entschädigungen, Beiträge",97236.700000,96152.367500,98641.250000
9,37,"Anteile, Entschädigungen, Beiträge",97236.700000,96152.367500,98641.250000
10,davon 363,Beiträge an eigene Anstalten,61524.700000,62965.850000,63322.300000
11,davon 364,Beiträge an gemischtwirtschaftliche Unternehmu...,2450.000000,2394.172000,2502.000000
12,davon 365,Beiträge an private Institutionen,133187.100000,129856.778000,135662.700000
13,davon 373,Durchl. Beiträge an eigene Anstalten,0.000000,0.000000,0.000000
14,davon 374,Durchl. Beiträge an gemischtwirtschaftliche Un...,0.000000,0.000000,0.000000
15,davon 375,Durchl. Beiträge an private Institutionen,700.000000,871.098000,924.300000
16,35,Einlagen in Spezialfinanzierungen/Fonds,14949.000000,22073.590000,16501.000000
17,389,Einlagen in das Eigenkapital,0.000000,33100.000000,0.000000
18,39,Interne Verrechnungen (Aufwand),21785.300000,22559.886000,23699.700000
19,3,Total Aufwand Laufende Rechnung,684415.000000,722246.758000,693144.800000
20,400 - 404,Direkte Steuern,304700.000000,340337.569000,314000.000000
21,405 - 407,Uebrige Steuern,19635.000000,21261.685000,20717.000000
22,42,Vermögenserträge,36867.100000,54553.306000,35386.900000
23,41,Konzessionen/Entgelte (Gebühren),35289.250000,35681.529500,35367.300000
24,43,Konzessionen/Entgelte (Gebühren),35289.250000,35681.529500,35367.300000
25,44,"Anteile, Rückerstattungen, Beiträge",51671.675000,55538.761000,54866.650000
26,45,"Anteile, Rückerstattungen, Beiträge",51671.675000,55538.761000,54866.650000
27,46,"Anteile, Rückerstattungen, Beiträge",51671.675000,55538.761000,54866.650000
28,47,"Anteile, Rückerstattungen, Beiträge",51671.675000,55538.761000,54866.650000
29,45,Entnahme aus Spezialfinanzierungen,8039.200000,6608.092000,4949.100000
30,489,Entnahmen aus dem Eigenkapital,0.000000,0.000000,0.000000
31,49,Interne Verrechnungen (Ertrag),21785.300000,22559.886000,23699.700000
32,4,Total Ertrag Laufende Rechnung,668291.800000,738838.641000,688953.900000
33,.,Saldo Laufende Rechnung,-16123.200000,16591.883000,-4190.900000
34,0,I N V E S T I T I O N S R E C H N U N G,0.000000,0.000000,0.000000
35,50,Sachgüter,13420.000000,9924.023000,21685.000000
36,54,Darlehen und Beteiligungen,60.000000,20169.200000,760.000000
37,56,"Investitionsbeiträge,übrige Investitionen",6436.666667,2456.520333,3503.333333
38,57,"Investitionsbeiträge,übrige Investitionen",6436.666667,2456.520333,3503.333333
39,58,"Investitionsbeiträge,übrige Investitionen",6436.666667,2456.520333,3503.333333
40,5,Total Ausgaben Investitionsrechnung,32790.000000,37462.784000,32955.000000
41,60,"Abgang Sachgüter, Nutzungsabgaben",0.000000,6938.685500,0.000000
42,61,"Abgang Sachgüter, Nutzungsabgaben",0.000000,6938.685500,0.000000
43,62,"Rückzahlung,Rückerstattung,Invest.-Beitr.",1292.033333,1265.274667,3065.433333
44,63,"Rückzahlung,Rückerstattung,Invest.-Beitr.",1292.033333,1265.274667,3065.433333
45,64,"Rückzahlung,Rückerstattung,Invest.-Beitr.",1292.033333,1265.274667,3065.433333
46,65,"Rückzahlung,Rückerstattung,Invest.-Beitr.",1292.033333,1265.274667,3065.433333
47,66,"Rückzahlung,Rückerstattung,Invest.-Beitr.",1292.033333,1265.274667,3065.433333
48,67,"Rückzahlung,Rückerstattung,Invest.-Beitr.",1292.033333,1265.274667,3065.433333
49,6,Total Einnahmen Investitionsrechnung,7752.200000,21469.019000,18392.600000
50,NI,Nettoinvestition,25037.800000,15993.765000,14562.400000
51,,Selbstfinanzierung,2302.500000,71811.870000,15135.000000
52,,Finanzierungsfehlbetrag(-)/-überschuss(+),-22735.300000,55818.105000,572.600000
53,,Konsolidierte Gesamtausgaben,658430.000000,656281.393000,662908.200000
54,0,Selbstfinanzierungsgrad,0.091961,4.489992,1.039320

In [16]:
new_df["Acc-ID"] = new_df["Acc-ID"].astype(str)

# Keep only rows with numeric 'Acc-ID'
new_df = new_df[new_df["Acc-ID"].str.isnumeric()]
new_df = new_df[new_df['Acc-ID'] != '0']

/var/folders/vy/kftwr_sx3kjbxvnd1nvc851m0000gn/T/ipykernel_84177/3362964305.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["Acc-ID"] = new_df["Acc-ID"].astype(str)

In [17]:
new_df

,Acc-ID,Name,Budget y,Realized,Budget y+1
0,30,Personalaufwand,174335.600000,173668.702000,174267.000000
1,31,Sachaufwand,59494.900000,58819.409000,58983.700000
3,34,Passivzinsen,2862.700000,1721.028000,2137.500000
4,330,Abschreibungen Finanzvermögen,3615.000000,3574.686000,3665.000000
6,34,"Anteile, Entschädigungen, Beiträge",97236.700000,96152.367500,98641.250000
7,35,"Anteile, Entschädigungen, Beiträge",97236.700000,96152.367500,98641.250000
8,36,"Anteile, Entschädigungen, Beiträge",97236.700000,96152.367500,98641.250000
9,37,"Anteile, Entschädigungen, Beiträge",97236.700000,96152.367500,98641.250000
16,35,Einlagen in Spezialfinanzierungen/Fonds,14949.000000,22073.590000,16501.000000
17,389,Einlagen in das Eigenkapital,0.000000,33100.000000,0.000000
18,39,Interne Verrechnungen (Aufwand),21785.300000,22559.886000,23699.700000
19,3,Total Aufwand Laufende Rechnung,684415.000000,722246.758000,693144.800000
22,42,Vermögenserträge,36867.100000,54553.306000,35386.900000
23,41,Konzessionen/Entgelte (Gebühren),35289.250000,35681.529500,35367.300000
24,43,Konzessionen/Entgelte (Gebühren),35289.250000,35681.529500,35367.300000
25,44,"Anteile, Rückerstattungen, Beiträge",51671.675000,55538.761000,54866.650000
26,45,"Anteile, Rückerstattungen, Beiträge",51671.675000,55538.761000,54866.650000
27,46,"Anteile, Rückerstattungen, Beiträge",51671.675000,55538.761000,54866.650000
28,47,"Anteile, Rückerstattungen, Beiträge",51671.675000,55538.761000,54866.650000
29,45,Entnahme aus Spezialfinanzierungen,8039.200000,6608.092000,4949.100000
30,489,Entnahmen aus dem Eigenkapital,0.000000,0.000000,0.000000
31,49,Interne Verrechnungen (Ertrag),21785.300000,22559.886000,23699.700000
32,4,Total Ertrag Laufende Rechnung,668291.800000,738838.641000,688953.900000
35,50,Sachgüter,13420.000000,9924.023000,21685.000000
36,54,Darlehen und Beteiligungen,60.000000,20169.200000,760.000000
37,56,"Investitionsbeiträge,übrige Investitionen",6436.666667,2456.520333,3503.333333
38,57,"Investitionsbeiträge,übrige Investitionen",6436.666667,2456.520333,3503.333333
39,58,"Investitionsbeiträge,übrige Investitionen",6436.666667,2456.520333,3503.333333
40,5,Total Ausgaben Investitionsrechnung,32790.000000,37462.784000,32955.000000
41,60,"Abgang Sachgüter, Nutzungsabgaben",0.000000,6938.685500,0.000000
42,61,"Abgang Sachgüter, Nutzungsabgaben",0.000000,6938.685500,0.000000
43,62,"Rückzahlung,Rückerstattung,Invest.-Beitr.",1292.033333,1265.274667,3065.433333
44,63,"Rückzahlung,Rückerstattung,Invest.-Beitr.",1292.033333,1265.274667,3065.433333
45,64,"Rückzahlung,Rückerstattung,Invest.-Beitr.",1292.033333,1265.274667,3065.433333
46,65,"Rückzahlung,Rückerstattung,Invest.-Beitr.",1292.033333,1265.274667,3065.433333
47,66,"Rückzahlung,Rückerstattung,Invest.-Beitr.",1292.033333,1265.274667,3065.433333
48,67,"Rückzahlung,Rückerstattung,Invest.-Beitr.",1292.033333,1265.274667,3065.433333
49,6,Total Einnahmen Investitionsrechnung,7752.200000,21469.019000,18392.600000